version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 15432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=my_tennis_club_S3cret
      - POSTGRES_USER=my_tennis_club__user
      - POSTGRES_DB=my_tennis_club_db